---
server:
    install: '1'
    packages: [vim, git]
    timezone: Europe/Madrid
    locale: es_ES.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: tweetrequester, ip: 192.168.33.102, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: rsync }
nginx:
    install: '1'
    docroot: /var/www/web
    servername: tweetrequester.vb
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt]
    peclpackages: [ZendOpcache, APC, redis, oauth]
xdebug:
    install: '1'
composer:
    install: '1'

